FROM quay.io/fedora/fedora-silverblue:41 AS base

FROM base AS clean_default_apps

RUN rpm-ostree uninstall --idempotent \
	default-editor \
	gnome-classic-session \
	gnome-initial-setup \
	gnome-tour \
	nano-default-editor \
	yelp \
	firefox \
	firefox-langpacks

FROM clean_default_apps AS install_basic_packages

# RUN rpm-ostree install --idempotent \
# 	https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
# 	https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

COPY files/vscode.repo /etc/yum.repos.d/vscode.repo
COPY files/ghostty.repo /etc/yum.repos.d/ghostty.repo

# RUN rpm-ostree uninstall --idempotent \
#         tuned \
#         tuned-ppd

RUN rpm-ostree install --idempotent \
	code \
	ddcutil \
	distrobox \
	dkms \
	efibootmgr \
	ghostty \
	git \
	gnome-browser-connector \
	gnome-tweaks \
	hdparm \
	just \
	kernel-devel \
	libgda \
	libgda-sqlite \
	libnotify \
	lm_sensors \
	neovim \
	nvme-cli \
	openssl \
	openssl-devel \
	powerstat \
	python3-pyclip \
	sdparm \
	smartmontools \
	sshfs \
	stow \
	waydroid \
	wl-clipboard

# tlp \
# tlp-rdw \
# mesa-va-drivers-freeworld \
# mesa-vdpau-drivers-freeworld \

# RUN rpm-ostree uninstall --idempotent \
# 	ffmpeg-free \
# 	libavcodec-free \
# 	libavdevice-free \
# 	libavfilter-free \
# 	libavformat-free \
# 	libavutil-free \
# 	libpostproc-free \
# 	libswresample-free \
# 	libswscale-free

# RUN rpm-ostree install --idempotent \
# 	ffmpeg \
# 	ffmpeg-libs \
# 	ffmpegthumbnailer \
# 	gstreamer1-libav

FROM install_basic_packages AS final_stage

COPY files/rpm-ostreed.conf /etc/rpm-ostreed.conf

RUN mkdir -p /etc/systemd/system/multi-user.target.wants && \
	ln -s /usr/lib/systemd/system/rpm-ostreed-automatic.timer /etc/systemd/system/timers.target.wants/

# RUN systemctl enable tlp.service
# RUN systemctl mask systemd-rfkill.service systemd-rfkill.socket

RUN rm -rf /var/* ~/.*
RUN rpm-ostree cleanup -m
RUN ostree container commit
